#!/usr/bin/env node

var fs = require('fs');
var write = fs.writeFileSync;
var read = fs.readFileSync;
var readdir = fs.readdirSync;
var unlink = fs.unlinkSync;

var red   = '\u001b[31m';
var blue  = '\u001b[36m';
var reset = '\u001b[0m';

var fileName = 'rename-operation.txt';

var before = readdir('.');

write(fileName, before.join('\r\n'));

var open = require('open');
open(fileName);

var readline = require('readline');

console.warn('press enter when you\'re done editing\n');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.on('line', function () {
  rl.close();
  var after = read(fileName).toString().replace(/\r/g, '').split('\n');
  unlink(fileName);
  if (before.length != after.length) {
    console.error(red + 'The number of lines changed from one file to the next' + reset);
    process.exit(1);
  }
  for (var i = 0; i < before.length; i++) {
    if (before[i] != after[i]) {
      try {
        fs.renameSync(before[i], after[i]);
        console.warn(blue + 'Rename ' + reset + before[i] + blue + ' to ' + reset + after[i]);
      } catch (ex) {
        console.error('\n' + red + 'FAIL: Rename ' + reset + before[i] + red + ' to ' + reset + after[i]);
        console.error('\n' + ex.message + '\n');
      }
    }
  }
});